### ISSUE TITLE
Which elm version ?

### ISSUE THREAD

**Issue by wadouk** [janjelinek/elm-performance-debugging#2]
Hi,

Try to use with a elm 0.19 build and nothing change in file, regexp match nothing.

Before trying to understand used regexp, found some lines
`var $elm$core$Array$compressNodes = F2(function(nodes, acc) {`
`var $elm$core$Tuple$first = function(_v0) {`

those lines should be changed to have named functions so tools could recognize ?

**Comment by janjelinek** [comment]
Hi, 
for me it was working for Elm version `0.19.1`. Do you have `--optimize` enabled? I always run this only without optimize flag enabled. 
You can always try to just check your output JS file, copy some piece of it (or whole) and check if regex will be working on it for example here https://regex101.com/ 

And for your question about regex itself. Yes, basically from your example it should take  name from variable and use it for function so it's no longer anonymous. 

```
// this 
var $elm$core$Array$compressNodes = F2(function(nodes, acc) {

// becomes this
var $elm$core$Array$compressNodes = F2(function __$elm$core$Array$compressNodes(nodes, acc) {
```

so you can see it in profiler and identify Elm module/functions behind it.

**Comment by wadouk** [comment]
I use [vite](https://vitejs.dev/) with [vite-plugin-elm@2.5.0](https://yarnpkg.com/package/vite-plugin-elm) that make `elm make` under the hood. The first stuff is to work with `optimize: false` of course and `vite` without minimize or compressing the output js bundle. 

The first regex match without `[^f]+` that seem to handle in the readme sample the new line/tabs between `F2` and `function`

Maybe there is a vite optimization to remove unnecessary new line in js output after build that fuck up the stuff.

Having the same as `this` to `become this` will help dig for the second regexp. Thanks

**Comment by wadouk** [comment]
This seem to handle the first case

`^var (\S+) = (\S+\()[^f]*function\s?\(`

Edit : but some replacement are weird, and saving content received from compile show there is some vite optimization
(left output from build, right the file received from elm previous step aka elm make)
![image](https://user-images.githubusercontent.com/787448/222751952-fc9254cd-ef46-4bf2-a0e2-039e51e20c72.png)

**Comment by wadouk** [comment]
Hum at the end, the regexp works as expected. Trying to apply to output of full build didn't work but applying at proper step is perfect. Thanks

``` javascript
function vitePluginElmProfiling() {
    return {
        name: 'elm-profiling',

        transform(src, id) {
            if (/\.elm$/.test(id)) {
                return {
                    code: src
                        .replaceAll(/var ([^=]+)( = F\d\([^f]+function)[^(]\(/gmi, 'var $1$2 __$1(')
                        .replaceAll(/(\sA\d\(\s+)([^,]+)(,\s+)(function[^(]+)\(/gm, '$1$2$3$4___$2(')
                    ,
                    map: null, // provide source map if available
                };
            }
            return {
                code: src,
                map: null, // provide source map if available
            };
        },
    }
}


```
